name: Crystal CI

on:
  push:
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [1.3.2, 1.2.2]
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Cache shards
        uses: actions/cache@v2
        with:
          path: |
            lib
            bin
          key: ${{ runner.os }}-shards-${{ hashFiles('**/shard.lock') }}
      - name: Install shards
        run: shards check || shards install --ignore-crystal-version
      - name: Check formatting
        run: crystal tool format
      - name: Linter
        run: ./bin/ameba
      - name: Run tests
        run: crystal spec --order=random
